import os

PATH_PROJECT = os.path.dirname(os.path.abspath(__file__))
PATH_HISTORY = os.path.join(PATH_PROJECT, 'history')
PATH_ZOO = PATH_PROJECT

APP_ALL = 'all'
APP_ZOO = 'zoo'
APP_SEC = 'security'
APP_FIN = 'finansis'
APP_KNO = 'know'
APP_DSP = 'dsp'
APP_HIS = 'history'
APP_ENC = 'en_decrypt'
APP_SQU = 'squirrel'
APP_TIM = 'timing'
APP_USR = 'user'
APP_STA = 'star'
APP_SPA = 'spatiotemporal'

EDP_DF = 'df'
EDP_PY = 'py'
EDP_IM = 'image'


class Apps(object):
    apps = {
        APP_SEC: (APP_SEC + ':tsunami', APP_SEC + ':suricata'),
        APP_ZOO: (APP_ZOO + ':images', ),
        APP_FIN: (APP_FIN + ':py', APP_FIN + ':df'),
        APP_KNO: (APP_KNO + ':site', APP_KNO + ':dom'),
        APP_DSP: (APP_DSP + ':yfd', APP_DSP + ':yft'),
        APP_HIS: (APP_HIS, ),
        APP_ENC: (APP_ENC, ),
        APP_SQU: (APP_SQU, ),
        APP_TIM: (APP_TIM, ),
        # APP_USR: (APP_USR, ),
        APP_STA: (APP_STA, ),
        APP_SPA: (APP_SPA, ),
    }


APPS_DEFAULT = (
    APP_DSP, APP_KNO, APP_HIS, APP_TIM,
    APP_ENC, APP_SPA, APP_FIN, APP_STA, APP_SQU,
)

# F_COMMANDS = 'COMMANDS'
# F_DEBUG = 'DEBUG'
F_FILE = 'FILE'
# F_HEADERS = 'HEADERS'
F_HIS_CURRENT = 'HIS-CURRENT'
F_HIS_BASE = 'HIS-BASE'
F_ID = 'ID'
# F_RESOURCES = 'META-RESOURCES'
F_MODE = 'MODE'
# F_MUTE = 'MUTE'
F_NODES = 'NODES'
F_PARAM = 'PARAM'
F_PARAMS = 'PARAMS'
F_PASS = 'PASS'
F_REPEAT = 'REPEAT'
F_REQUIRE_LOCK = 'REQUIRE-LOCK'
F_RESOURCE = 'RESOURCE'
F_ROLES = 'ROLES'
F_SETTING = 'SETTING'
F_RUNNING = 'RUNNING'
F_SLEEP = 'SLEEP'
F_SUCCESS = 'SUCCESS'
O_TASK = 'TASK'
O_BLOCK = 'BLOCK'
O_COMMAND = 'COMMAND'
# F_TASKS = 'TASKS'
F_TIPS = 'TIPS'
F_TITLE = 'TITLE'
F_ITEMS = 'ITEMS'
F_SUDO = 'SUDO'

O_YFT = 'YFT'
O_YFD = 'YFD'
O_CONF = 'CONF'
O_XML = 'XML'
O_SH = 'SH'
O_CWD = 'CWD'
O_SUDO = 'SUDO'
O_EXTRACT = 'EXTRACT'
O_EXTRACT_KEY = 'KEY'
O_EXTRACT_VALUE = 'VALUE'
O_EXTRACT_START = 'START'
O_EXTRACT_START_WITH = 'START_WITH'
O_EXTRACT_END = 'END'
O_FUNC = 'FUNC'
O_TEXT = 'TEXT'
O_TEXT_IF_NOT_EXIST = '__IF_NOT_EXIST'
O_TEXT_REPLACE_THIS = '__REPLACE_THIS'
O_TEXT_BY = '__BY'
O_TEXT_BY_IF_NOT_EXIST = '__BY_IF_NOT_EXIST'
O_TEXT_AFTER_THIS = '__AFTER_THIS'
O_TEXT_INSERT = '__INSERT'
O_TEXT_APPEND = '__APPEND'
O_TEXT_APPEND_IF_NOT_EXIST = '__APPEND_IF_NOT_EXIST'
O_TEXT_IF_LINE_STARTSWITH = '__IF_LINE_STARTSWITH'
O_TEXT_COMMENT_IT = '__COMMENT_IT'
O_SLEEP = 'SLEEP'
O_AFTER = 'AFTER'
O_BEFORE = 'BEFORE'
O_WAITE = 'WAITE'
O_WAITE_NODES_ON_LINE = 'WAITE_NODES_ON_LINE'
O_WAITE_NODE_PORT_ON = 'WAITE_NODE_PORT_ON'
O_SYNC_DOWNLOAD = 'DOWNLOAD'
O_SYNC_UPLOAD = 'UPLOAD'
O_SYNC_SRC = '__SRC'
O_SYNC_DST = '__DST'
O_SYNC_SUFFIX = '__SUFFIX'
O_SYNC_DATE_FILTER = '__DATE'
O_HTTP = 'HTTP'
O_HTTP_GET = 'GET'
O_HTTP_POST = 'POST'
O_HTTP_PATCH = 'PATCH'
O_HTTP_DELETE = 'DELETE'
O_HTTP_HEADERS = 'HEADERS'
O_HTTP_JSON = 'JSON'
O_HTTP_DATA = 'DATA'
O_HTTP_SAF = 'SAF'
O_EXTRACTS = 'EXTRACTS'
O_EXTRACTS_FILE = 'FILE'
O_EXTRACTS_TYPE = 'TYPE'
O_EXTRACTS_TYPE_STRING = 'STRING'
O_EXTRACTS_TYPE_JSON = 'JSON'
O_EXTRACTS_EXTRACT = 'EXTRACT'
O_STACK = 'STACK'
O_STACK_META_RESOURCE = 'META-RESOURCES'
O_STACK_URI = 'URI'
O_STACK_AUTH_TYPE = 'AUTH-TYPE'
O_STACK_AUTH_TOKEN = 'TOKEN'
O_STACK_AUTH_SESSION = 'SESSION'
O_STACK_AUTH_NONE = 'NONE'
O_STACK_LIST_KEY = 'LIST-KEY'
O_STACK_CODE = 'CODE'
O_STACK_CODE_DEFAULT = 'DEFAULT'
O_STACK_PARAM = 'PARAM'
O_STACK_PARAMS = 'PARAMS'
O_STACK_EXPECTS = 'EXPECTS'
O_STACK_EXPECTS_COUNT = 'COUNT'

O_SHOWS = 'SHOWS'
O_SHOW_LOG = 'LOG'
O_SHOW_REQ_BODY = 'REQ-BODY'
O_SHOW_REQ_HEADERS = 'REQ-HEADERS'
O_SHOW_RSP_DATA = 'RSP-DATA'
O_SHOW_RSP_DATA_TEXT = 'RSP-DATA-TEXT'
O_SHOW_RSP_DATA_JSON = 'RSP-DATA-JSON'
O_SHOW_RSP_HEADERS = 'RSP-HEADERS'
O_SHOW_RSP_COOKIES = 'RSP-COOKIES'
O_SHOW_SETTING = 'SETTING'
O_SHOW_RUNNING = 'RUNNING'
O_SHOW_COST = 'COST'

O_SHOW_SH = 'SH'
O_SHOW_SH_CWD = 'SH.CWD'
O_SHOW_SH_CMD = 'SH.CMD'
O_SHOW_SH_SUDO = 'SH.SUDO'
O_SHOW_SH_STDOUT = 'SH.STDOUT'
O_SHOW_SH_STDERR = 'SH.STDERR'

O_SHOW_SLEEP = 'SLEEP'

O_SHOW_HTTP = 'HTTP'
O_SHOW_HTTP_METHOD = 'HTTP.METHOD'
O_SHOW_HTTP_URL = 'HTTP.URL'
O_SHOW_HTTP_REQ_HEADERS = 'HTTP.REQ.HEADERS'
O_SHOW_HTTP_REQ_PARAM = 'HTTP.REQ.PARAM'
O_SHOW_HTTP_SAF = 'HTTP.SAF'
O_SHOW_HTTP_RSP_CODE = 'HTTP.RSP.CODE'
O_SHOW_HTTP_RSP_DATA = 'HTTP.RSP.DATA'

O_SHOW_UPLOAD = 'UPLOAD'
O_SHOW_UPLOAD_DST = 'UPLOAD.DST'
O_SHOW_UPLOAD_SRC = 'UPLOAD.SRC'
O_SHOW_UPLOAD_SUFFIX = 'UPLOAD.SUFFIX'
O_SHOW_UPLOAD_SYNC = 'UPLOAD.SYNC'
O_SHOW_UPLOAD_DATE = 'UPLOAD.DATE'

O_SHOW_TEXT = 'TEXT'
O_SHOW_TEXT_PASS = 'TEXT.PASS'
O_SHOW_TEXT_EDIT = 'TEXT.EDIT'
O_SHOW_TEXT_FILE = 'TEXT.FILE'

O_SHOW_CONF = 'CONF'
O_SHOW_FUNC = 'FUNC'
O_SHOW_EXTRACTS = 'EXTRACTS'

O_SHOW_NODE = 'NODE'
O_SHOW_TIME = 'TIME'
O_SHOW_TIPS = 'TIPS'
O_SHOW_TAGS = 'TAGS'
O_SHOW_WARNING = 'WARNING'

O_SHOW_STACK = 'STACK'
O_SHOW_STACK_LOG = 'STACK.LOG'
O_SHOW_STACK_URL = 'STACK.URL'
O_SHOW_STACK_API = 'STACK.API'
O_SHOW_STACK_CODE = 'STACK.CODE'
O_SHOW_STACK_REQ_PARAM = 'STACK.REQ.PARAM'
O_SHOW_STACK_REQ_HEADERS = 'STACK.REQ.HEADERS'
O_SHOW_STACK_RSP_HEADERS = 'STACK.RSP.HEADERS'
O_SHOW_STACK_RSP_DATA = 'STACK.RSP.DATA'
O_SHOW_STACK_RSP_COOKIES = 'STACK.RSP.COOKIES'
O_SHOW_ALL = 'ALL'
O_SHOW_FILEDS = (O_SHOW_CONF, O_SHOW_COST,
                 O_SHOW_EXTRACTS,
                 O_SHOW_FUNC,
                 O_SHOW_HTTP,
                 O_SHOW_NODE,
                 O_SHOW_STACK, O_SHOW_SH, O_SHOW_SLEEP,
                 O_SHOW_TAGS, O_SHOW_TIPS, O_SHOW_TEXT, O_SHOW_TIME,
                 O_SHOW_UPLOAD,
                 O_SHOW_WARNING,
                 )
O_PAUSE = 'PAUSE'
O_EXTEND = 'EXTEND'
O_HOSTS = 'HOSTS'
O_HOST_DEFAULT = 'HOST_DEFAULT'
O_HOST_LOGS = 'HOST_LOGS'
O_NODES = 'NODES'
O_ROLES = 'ROLES'
O_STACK_APIS = 'STACK_APIS'
O_STACK_SERVICES = 'STACK_SERVICES'
O_GID = 'GID'
O_SERVICE_TN1 = 'tn'
O_SERVICE_TN2 = 'tn2'
O_SERVICE_TNs = (O_SERVICE_TN1, O_SERVICE_TN2)
O_HEADERS = 'HEADERS'
O_SEQUENCES = 'SEQUENCES'
O_LINES = 'LINES'
O_LINES_KEY = 'KEY'
O_LINES_VALUE = 'VALUE'
O_LINES_START = 'START'
O_LINES_START_WITH = 'START_WITH'
O_LINES_END = 'END'
O_LINES_STRIP = 'STRIP'
# FILTER:
#   ANY:
#     - 'IS_TRUE({{shared}})'
#     - 'IS_FALSE({{is_default}})'
#     - 'IS_DICT({{shared}})'
#     - 'IS_LIST({{is_default}})'
#     - 'EQ({{shared}}, 1)'
#     - 'NE({{name}}, default)'
#     - 'GT({{shared}}, 1)'
#     - 'GE({{is_default}}, 1)'
#     - 'LT({{shared}}, 1)'
#     - 'LE({{is_default}}, 1)'
#     - 'CONTAIN({{shared}}, a)'
#     - 'NCONTAIN({{shared}}, b)'
#     - 'LENGTH({{shared}}, 1)'
#     - 'ANY':
#         - 'EQ({{shared}}, 1)'
#         - 'EQ({{shared}}, 2)'
#     - 'ALL':
#         - 'EQ({{shared}}, 1)'
#         - 'EQ({{shared}}, 2)'
O_FILTER = 'FILTER'
O_FILTER_ALL = 'ALL'
O_FILTER_ANY = 'ANY'
O_FILTER_NOT = 'NOT'
O_FILTER_CONTAIN = 'CONTAIN'
O_FILTER_NCONTAIN = 'NCONTAIN'
O_FILTER_IS_TRUE = 'IS_TRUE'
O_FILTER_IS_FALSE = 'IS_FALSE'
O_FILTER_IS_DICT = 'IS_DICT'
O_FILTER_IS_LIST = 'IS_LIST'
O_FILTER_EQ = 'EQ'
O_FILTER_NE = 'NE'
O_FILTER_LE = 'LE'
O_FILTER_LT = 'LT'
O_FILTER_GT = 'GT'
O_FILTER_GE = 'GE'
O_FILTER_LENGTH = 'LENGTH'
O_FILTER_CONNECTORS = (O_FILTER_ALL, O_FILTER_ANY, O_FILTER_NOT)
O_FILTER_CONDITIONALS = (
    O_FILTER_CONTAIN, O_FILTER_NCONTAIN,
    O_FILTER_IS_TRUE, O_FILTER_IS_FALSE,
    O_FILTER_IS_DICT, O_FILTER_IS_LIST,
    O_FILTER_EQ, O_FILTER_NE, O_FILTER_LE, O_FILTER_LT,
    O_FILTER_GT, O_FILTER_GE, O_FILTER_LENGTH
)

O_TIMING = 'TIMING'
O_TIMING_STATUS = 'STATUS'
O_TIMING_TRIGGER = 'TRIGGER'

V_LOCAL = ('LOCAL', 'LOCALHOST', '', '127.0.0.1')
O_NOLOG = 'NOLOG'
F_STARS = 'STARS'
F_BOOKMARKS = 'BOOKMARKS'

O_INST = 'INST'
O_TIPS = 'TIPS'
O_TAGS = 'TAGS'
O_ID = 'ID'
O_IGNORE = 'IGNORE'
O_PSW = 'PSW'
O_DOWNLOAD = 'DOWNLOAD'
O_UPLOAD = 'UPLOAD'
O_EXTRACTS = 'EXTRACTS'
